name: spotify_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  spotify: ^0.13.7
  webview_flutter: ^4.2.1 
  get_it: ^7.6.0
  url_launcher: ^6.3.1
  app_links: ^6.3.3
  oauth2_client: ^3.3.0
  shared_preferences: ^2.3.4
  flutter_web_auth_2: ^3.1.2
  http: ^1.2.2
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  flutter_webrtc: ^0.12.5
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  cloud_firestore_web: ^4.4.0
  go_router: ^14.6.2
  share_plus: ^10.1.3
  peerdart: any
  flutter_bloc: ^8.1.6
  vibration: ^2.0.1
  flutter_dotenv: ^5.2.1
  
dependency_overrides:
  flutter_webrtc: ^0.12.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0
  leancode_lint: ^14.2.0
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - secrets.env
    

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icon.png" 