// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl4uEctw1zJOZi2epvUIrXbxSs2xLdt0E',
    appId: '1:269271335801:web:69376bccfee3ea629725a8',
    messagingSenderId: '269271335801',
    projectId: 'groovecheck-6bbf7',
    authDomain: 'groovecheck-6bbf7.firebaseapp.com',
    storageBucket: 'groovecheck-6bbf7.firebasestorage.app',
    measurementId: 'G-NV4FZEGWLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyQ1ijG7CGPdEq5Nrhc01rGcN-JIOKD7o',
    appId: '1:269271335801:android:08c948dfd801a5699725a8',
    messagingSenderId: '269271335801',
    projectId: 'groovecheck-6bbf7',
    storageBucket: 'groovecheck-6bbf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCb8rI0HI2QhdjJ5D7FKk2_6VZI5IngAk',
    appId: '1:269271335801:ios:962bacc4f0a0f3ee9725a8',
    messagingSenderId: '269271335801',
    projectId: 'groovecheck-6bbf7',
    storageBucket: 'groovecheck-6bbf7.firebasestorage.app',
    iosBundleId: 'com.example.spotifyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCb8rI0HI2QhdjJ5D7FKk2_6VZI5IngAk',
    appId: '1:269271335801:ios:962bacc4f0a0f3ee9725a8',
    messagingSenderId: '269271335801',
    projectId: 'groovecheck-6bbf7',
    storageBucket: 'groovecheck-6bbf7.firebasestorage.app',
    iosBundleId: 'com.example.spotifyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl4uEctw1zJOZi2epvUIrXbxSs2xLdt0E',
    appId: '1:269271335801:web:c1670bcf956731f19725a8',
    messagingSenderId: '269271335801',
    projectId: 'groovecheck-6bbf7',
    authDomain: 'groovecheck-6bbf7.firebaseapp.com',
    storageBucket: 'groovecheck-6bbf7.firebasestorage.app',
    measurementId: 'G-J0GEVQ6TE3',
  );
}
